spring.application.name=api-gateway
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs

server.port=8080

eureka.client.service-url.defaultZone = http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# localhost
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

eureka.instance.status-page-url=http://localhost:8080/webjars/swagger-ui/index.html#/
eureka.instance.health-check-url=http://localhost:8080/actuator/health

# Add these new properties
#Habilita el DiscoveryClient Route Definition Locator en el Gateway.
#Esto permite que el Gateway descubra automáticamente los servicios registrados en Eureka
# y cree rutas dinámicas para ellos.
spring.cloud.gateway.discovery.locator.enabled=true
# Convierte los nombres de los servicios a minúsculas.
# Esto es útil porque Eureka registra los nombres de los servicios en mayúsculas por defecto
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#springdoc.swagger-ui.urls[0].url=/v3/api-docs
#springdoc.swagger-ui.urls[0].name=API Gateway